spring.application.name=bff.agendador-tarefas


usuario.url=localhost:8080/usuario

agendador-tarefas-back-and.url=http://localhost:8081

server.port=8083


notificacao.url=localhost:8082/email


cron.horario=0 0/5 * * * ?

usuario.email=jadeiltondm@gmail.com

usuario.senha=12345

